### ISSUE TITLE
Roadmap / todos

### ISSUE THREAD

**Issue by vadimnazarov** [imminfo/ymir#1]
- [ ] Implement SAAG (Single Alignment Assembly Graph).
  - [ ] Implement scenario iterator.
  - [ ] Implement forward probabilities.
  - [ ] Implement backward probabilities.
- [ ] Implement SAAG builder.
  - [ ] Implement VJ SAAG builder.
  - [ ] Compute TCR alpha chain assembly probabilities with deterministic alignment and compare speed with previous implementation.
  - [ ] Implement VDJ SAAG builder.
  - [ ] Compute TCR beta chain assembly probabilities with deterministic alignment and compare speed with previous implementation.
- [ ] Implement MAAG (Multi-Alignment Assembly Graph).
  - [ ] Implement full probability computing.
  - [ ] Implement slice probability computing.
  - [ ] Implement scenario iterator.
  - [ ] Implement forward probabilities for slice.
  - [ ] Implement backward probabilities for slice.
- [ ] Implement MAAG builder.
- [ ] Implement EM algorithm.
